name: Routine Push Check
run-name: ${{ github.actor }} push to "${{ github.ref_name }}" on ${{ github.sha }}
on:
  push:
    branches:
      - '*'
      - '!dev'
      - '!main'
jobs:
  Routine_Check_for_Commit:
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/Check_On_Commit.yml@master
    with:
      image_to_use: ghcr.io/ruiheesi/single-cell-rna-r4:latest