name: Gitflow Action for R Package Development
run-name: ${{ github.actor }} now ${{ github.event_name }} to ${{ github.ref_name }}

on:
  push:
    branches: ['*', '!dev', '!main']
    
  pull_request:
    types: ['opened', 'closed']
    branches: ['main', 'release*']

jobs:
  Activating_Parser:
    env:
      set_image_to_be_used: ghcr.io/ruiheesi/dsp-r4:latest
      action_version: main
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/parser.yml@master
    with:
      image_to_use: "${{ env.image_to_be_used }}"
      verions_to_use: "${{ env.action_version }}"
      
